project_id = "hhayhqcibylidimfortv"

[functions.get-session]
verify_jwt = false

[functions.track-success]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.posthog-identity-hash]
verify_jwt = false

